# Generated by Django 5.1.14 on 2025-12-06 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ERP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_status', models.CharField(choices=[('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='to_be_delivered', max_length=20)),
                ('delivery_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('delivery_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_ordered', models.IntegerField()),
                ('quantity_delivered', models.IntegerField(default=0)),
                ('quantity_accepted', models.IntegerField(default=0)),
                ('inspection_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Discrepancy',
            fields=[
                ('disc_id', models.AutoField(primary_key=True, serialize=False)),
                ('disc_condition', models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged'), ('missing', 'Missing'), ('excess', 'Excess'), ('wrong', 'Wrong Item')], max_length=20)),
                ('disc_quantity', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('damage_type', models.TextField(blank=True, null=True)),
                ('missing_reason', models.TextField(blank=True, null=True)),
                ('excess_action', models.TextField(blank=True, null=True)),
                ('correct_item', models.TextField(blank=True, null=True)),
                ('inspection_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inspection_discrepancy',
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.CreateModel(
            name='Discrepancy_Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('quantity', 'Quantity Discrepancy'), ('quality', 'Quality Issue'), ('damage', 'Damaged Goods'), ('missing', 'Missing Items')], max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receiving_Memo',
            fields=[
                ('rm_id', models.AutoField(primary_key=True, serialize=False)),
                ('rm_date', models.DateTimeField()),
                ('rm_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rm_pdf', models.FileField(blank=True, null=True, upload_to='receiving_memos/')),
            ],
            options={
                'db_table': 'receiving_memo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Return_Request',
            fields=[
                ('return_id', models.AutoField(primary_key=True, serialize=False)),
                ('return_reason', models.TextField()),
                ('return_date', models.DateTimeField()),
                ('return_status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('quantity_to_return', models.IntegerField()),
                ('return_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Acknowledgment_Receipt',
            fields=[
                ('ar_id', models.AutoField(primary_key=True, serialize=False)),
                ('ar_number', models.CharField(max_length=50, unique=True)),
                ('ar_date', models.DateTimeField()),
                ('ar_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_acknowledgment_receipts', to='ERP.user')),
            ],
        ),
    ]
