# Generated by Django 5.1.14 on 2025-12-06 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ERP', '0001_initial'),
        ('Property_Custodian', '0001_initial'),
        ('Purchasing', '0001_initial'),
        ('Requisition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries_made', to='Purchasing.supplier'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='inspected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_deliveries', to='ERP.user'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchasing.purchase_order'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Requisition.requisition'),
        ),
        migrations.AddField(
            model_name='acknowledgment_receipt',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Property_Custodian.delivery'),
        ),
        migrations.AddField(
            model_name='deliveryitem',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERP.branch'),
        ),
        migrations.AddField(
            model_name='deliveryitem',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Property_Custodian.delivery'),
        ),
        migrations.AddField(
            model_name='deliveryitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.product'),
        ),
        migrations.AddField(
            model_name='deliveryitem',
            name='purchase_order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchasing.purchase_order_item'),
        ),
        migrations.AddField(
            model_name='discrepancy',
            name='inspected_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.user'),
        ),
        migrations.AddField(
            model_name='discrepancy',
            name='po_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchasing.purchase_order_item'),
        ),
        migrations.AddField(
            model_name='discrepancy',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.product'),
        ),
        migrations.AddField(
            model_name='discrepancy',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchasing.purchase_order'),
        ),
        migrations.AddField(
            model_name='discrepancy_report',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Property_Custodian.delivery'),
        ),
        migrations.AddField(
            model_name='discrepancy_report',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_discrepancies', to='ERP.user'),
        ),
        migrations.AddField(
            model_name='receiving_memo',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Property_Custodian.delivery'),
        ),
        migrations.AddField(
            model_name='receiving_memo',
            name='generated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_receiving_memos', to='ERP.user'),
        ),
        migrations.AddField(
            model_name='receiving_memo',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Purchasing.purchase_order'),
        ),
        migrations.AddField(
            model_name='receiving_memo',
            name='requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Requisition.requisition'),
        ),
        migrations.AddField(
            model_name='return_request',
            name='delivery_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Property_Custodian.deliveryitem'),
        ),
        migrations.AddField(
            model_name='return_request',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_returns', to='ERP.user'),
        ),
        migrations.AlterUniqueTogether(
            name='deliveryitem',
            unique_together={('delivery', 'purchase_order_item')},
        ),
    ]
