# Generated by Django 5.1.7 on 2025-11-29 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0011_remove_delivery_po_id_remove_delivery_received_by_and_more'),
        ('Property_Custodian', '0002_remove_purchase_order_po_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discrepancy',
            fields=[
                ('disc_id', models.AutoField(primary_key=True, serialize=False)),
                ('disc_condition', models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged'), ('missing', 'Missing'), ('excess', 'Excess'), ('wrong', 'Wrong Item')], max_length=20)),
                ('disc_quantity', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('damage_type', models.TextField(blank=True, null=True)),
                ('missing_reason', models.TextField(blank=True, null=True)),
                ('excess_action', models.TextField(blank=True, null=True)),
                ('correct_item', models.TextField(blank=True, null=True)),
                ('inspection_date', models.DateTimeField(auto_now_add=True)),
                ('inspected_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.user')),
                ('po_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Property_Custodian.purchase_order_item')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Property_Custodian.purchase_order')),
            ],
            options={
                'db_table': 'inspection_discrepancy',
                'ordering': ['-inspection_date'],
            },
        ),
    ]
