# Generated by Django 5.1.7 on 2025-11-29 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property_Custodian', '0003_discrepancy'),
        ('Requisition', '0004_alter_requisition_req_substatus_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receiving_memo',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='receiving_memo',
            name='rm_number',
        ),
        migrations.AddField(
            model_name='receiving_memo',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Property_Custodian.purchase_order'),
        ),
        migrations.AddField(
            model_name='receiving_memo',
            name='requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Requisition.requisition'),
        ),
        migrations.AddField(
            model_name='receiving_memo',
            name='rm_pdf',
            field=models.FileField(blank=True, null=True, upload_to='receiving_memos/'),
        ),
        migrations.AlterField(
            model_name='receiving_memo',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Property_Custodian.delivery'),
        ),
        migrations.AlterModelTable(
            name='receiving_memo',
            table='receiving_memo',
        ),
    ]
