# Generated by Django 5.1.7 on 2025-12-04 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0011_remove_delivery_po_id_remove_delivery_received_by_and_more'),
        ('Property_Custodian', '0004_alter_receiving_memo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Deliveries'},
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='po_id',
            new_name='purchase_order',
        ),
        migrations.AddField(
            model_name='delivery',
            name='condition_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries_made', to='ERP.user'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ERP.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='quantity_accepted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='delivery',
            name='quantity_delivered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='delivery',
            name='quantity_ordered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='delivery',
            name='quantity_rejected',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_status',
            field=models.CharField(choices=[('to_be_delivered', 'To Be Delivered'), ('delivered', 'Delivered')], default='to_be_delivered', max_length=20),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries_received', to='ERP.user'),
        ),
    ]
