# Generated by Django 5.1.7 on 2025-12-04 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0011_remove_delivery_po_id_remove_delivery_received_by_and_more'),
        ('Property_Custodian', '0006_remove_delivery_condition_notes_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Delivery_Item',
            new_name='DeliveryItem',
        ),
    ]
