# Generated by Django 5.1.7 on 2025-12-04 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property_Custodian', '0007_rename_delivery_item_deliveryitem'),
        ('Requisition', '0004_alter_requisition_req_substatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order_item',
            name='requisition_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_items', to='Requisition.requisitionitem'),
        ),
    ]
