# Generated by Django 5.1.7 on 2025-12-05 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Property_Custodian', '0008_purchase_order_item_requisition_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='expected_date',
        ),
    ]
