# Generated by Django 5.1.7 on 2025-12-05 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0011_remove_delivery_po_id_remove_delivery_received_by_and_more'),
        ('Property_Custodian', '0009_remove_delivery_expected_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryitem',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERP.branch'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_status',
            field=models.CharField(choices=[('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='to_be_delivered', max_length=20),
        ),
    ]
