# Generated by Django 5.1.14 on 2025-12-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requisition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionstatustimeline',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
