# Generated by Django 5.1.14 on 2025-11-17 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ERP', '0009_price_history_product_specification'),
        ('Requisition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('sup_id', models.AutoField(primary_key=True, serialize=False)),
                ('sup_name', models.CharField(max_length=255)),
                ('sup_contact_person', models.CharField(max_length=255)),
                ('sup_phone', models.CharField(max_length=50)),
                ('sup_email', models.EmailField(max_length=254, unique=True)),
                ('sup_address', models.TextField()),
                ('sup_payment_terms', models.CharField(max_length=100)),
                ('sup_delivery_terms', models.CharField(max_length=100)),
                ('sup_is_active', models.BooleanField(default=True)),
                ('sup_created_at', models.DateTimeField(auto_now_add=True)),
                ('sup_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('po_id', models.AutoField(primary_key=True, serialize=False)),
                ('po_status', models.CharField(max_length=50)),
                ('po_order_date', models.DateField()),
                ('po_eta', models.DateField()),
                ('po_total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('po_approval_date', models.DateField(blank=True, null=True)),
                ('po_rejection_reason', models.TextField(blank=True, null=True)),
                ('po_created_at', models.DateTimeField(auto_now_add=True)),
                ('po_pdf', models.FileField(blank=True, null=True, upload_to='purchase_orders/')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.branch')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Requisition.requisition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.user')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchasing.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('po_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('po_item_ordered_quantity', models.IntegerField()),
                ('po_item_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('po_item_line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchasing.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierCategory',
            fields=[
                ('sup_cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.product_category')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchasing.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('sup_prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('sup_prod_code', models.CharField(max_length=100)),
                ('sup_prod_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sup_prod_last_updated_price', models.DateField()),
                ('sup_is_available', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchasing.supplier')),
            ],
        ),
    ]
