# Generated by Django 5.1.14 on 2025-11-23 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ERP', '0009_price_history_product_specification'),
        ('Requisition', '0004_alter_requisition_req_substatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('sup_id', models.AutoField(primary_key=True, serialize=False)),
                ('sup_name', models.CharField(max_length=255)),
                ('sup_phone', models.CharField(max_length=50)),
                ('sup_email', models.CharField(blank=True, max_length=255, null=True)),
                ('sup_address', models.TextField(blank=True, null=True)),
                ('sup_payment_terms', models.TextField(blank=True, null=True)),
                ('sup_delivery_terms', models.TextField(blank=True, null=True)),
                ('sup_is_active', models.BooleanField(default=True)),
                ('sup_created_at', models.DateTimeField(auto_now_add=True)),
                ('sup_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Order',
            fields=[
                ('po_id', models.AutoField(primary_key=True, serialize=False)),
                ('po_status', models.CharField(max_length=50)),
                ('po_date_sent_to_sup', models.DateField(blank=True, null=True)),
                ('po_eta', models.DateField(blank=True, null=True)),
                ('po_total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('po_approval_date', models.DateField(blank=True, null=True)),
                ('po_rejection_reason', models.TextField(blank=True, null=True)),
                ('po_created_at', models.DateTimeField(auto_now_add=True)),
                ('po_pdf', models.FileField(blank=True, null=True, upload_to='po_pdfs/')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.branch')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Requisition.requisition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.user')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchasing.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Order_Item',
            fields=[
                ('po_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('po_item_ordered_quantity', models.IntegerField()),
                ('po_item_unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('po_item_line_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchasing.purchase_order')),
            ],
        ),
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('rfq_id', models.AutoField(primary_key=True, serialize=False)),
                ('rfq_created_at', models.DateTimeField(auto_now_add=True)),
                ('rfq_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Requisition.requisition')),
            ],
        ),
        migrations.CreateModel(
            name='RFQ_Item',
            fields=[
                ('rfq_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('rfq_item_req_qty', models.IntegerField(default=0)),
                ('rfq_item_req_uom', models.CharField(max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.product')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Requisition.requisition')),
            ],
        ),
        migrations.CreateModel(
            name='RFQ_Supplier',
            fields=[
                ('rfq_sup_id', models.AutoField(primary_key=True, serialize=False)),
                ('rfq_date_sent', models.DateTimeField(auto_now_add=True)),
                ('date_responded', models.DateTimeField(blank=True, null=True)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Requisition.requisition')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchasing.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_Category',
            fields=[
                ('sup_cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.product_category')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchasing.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_Product',
            fields=[
                ('sup_prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('sup_prod_code', models.CharField(max_length=50)),
                ('sup_prod_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sup_prod_last_updated_price', models.DateTimeField(auto_now_add=True)),
                ('sup_prod_is_active', models.BooleanField(default=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchasing.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_Quotation',
            fields=[
                ('sup_qtn_id', models.AutoField(primary_key=True, serialize=False)),
                ('sup_qtn_total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sup_qtn_eta', models.DateField(blank=True, null=True)),
                ('sup_qtn_valid_until', models.DateField(blank=True, null=True)),
                ('sup_qtn_pdf', models.FileField(blank=True, null=True, upload_to='supplier_quotations/')),
                ('sup_qtn_created_at', models.DateTimeField(auto_now_add=True)),
                ('rfq_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchasing.rfq_supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_Quotation_Item',
            fields=[
                ('sup_qtn_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('sup_qtn_item_unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.product')),
                ('rfq_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchasing.rfq_item')),
                ('supplier_quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchasing.supplier_quotation')),
            ],
        ),
    ]
