# Generated by Django 5.1.14 on 2025-11-24 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0009_price_history_product_specification'),
        ('Purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='sup_contact_person',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='supplier_product',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP.product'),
        ),
    ]
