# Generated by Django 5.2.8 on 2025-11-30 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0009_price_history_product_specification'),
        ('Purchasing', '0002_supplier_sup_contact_person_supplier_product_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier_Product_PriceHistory',
            fields=[
                ('price_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERP.user')),
                ('supplier_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='Purchasing.supplier_product')),
            ],
        ),
    ]
