# Generated by Django 5.1.14 on 2025-12-06 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchasing', '0003_purchase_order_po_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order',
            name='rfq_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Purchasing.rfq_supplier'),
        ),
        migrations.AddField(
            model_name='purchase_order',
            name='supplier_quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Purchasing.supplier_quotation'),
        ),
    ]
