# Generated by Django 5.1.14 on 2025-12-02 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0009_price_history_product_specification'),
        ('Purchasing', '0003_remove_purchase_order_po_status_and_more'),
        ('Requisition', '0004_alter_requisition_req_substatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfq_item',
            name='requisition',
        ),
        migrations.AddField(
            model_name='rfq_item',
            name='requisition_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfq_items', to='Requisition.requisitionitem'),
        ),
        migrations.AddField(
            model_name='rfq_item',
            name='rfq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Purchasing.rfq'),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='po_main_status',
            field=models.CharField(choices=[('PENDING_CUSTODIAN', 'Pending Custodian Approval'), ('PENDING_TOP_MGMT', 'Pending Top Management Approval'), ('APPROVED_REQUISITION', 'Approved Requisition'), ('PO_APPROVAL', 'PO Approval'), ('TO_BE_DELIVERED', 'To be Delivered'), ('INSPECTION', 'Inspection'), ('FULFILLED', 'Request Fulfilled')], default='PO_APPROVAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='po_substatus',
            field=models.CharField(choices=[('RFQ_CREATED', 'RFQ Created'), ('QUOTATIONS_COMPLETED', 'Quotations Completed'), ('PENDING_PO', 'Pending Purchase Order'), ('PO_CUSTODIAN_APPROVAL', 'Custodian reviewed and approved'), ('PO_TOP_MANAGEMENT_APPROVAL', 'Approved by Top Management'), ('PO_APPROVED', 'PO Approved'), ('PO_SENT_TO_SUPPLIER', 'PO Sent to Supplier'), ('PRODUCTS_RECEIVED', 'Products Received'), ('INSPECTING', 'Inspecting'), ('IN_TRANSIT', 'In Transit'), ('NONE', 'None')], default='NONE', max_length=100),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='rfq_created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.user'),
        ),
        migrations.AlterField(
            model_name='rfq_supplier',
            name='rfq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchasing.rfq'),
        ),
    ]
