# Generated by Django 5.1.7 on 2025-11-29 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0010_alter_branch_branch_name_delivery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='po_id',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='received_by',
        ),
        migrations.RemoveField(
            model_name='receiving_memo',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='discrepancy_report',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='delivery_product',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='delivery_product',
            name='flagged_by',
        ),
        migrations.RemoveField(
            model_name='delivery_product',
            name='product',
        ),
        migrations.RemoveField(
            model_name='return_request',
            name='delivery_product',
        ),
        migrations.RemoveField(
            model_name='discrepancy_report',
            name='reported_by',
        ),
        migrations.RemoveField(
            model_name='purchase_order',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='receiving_memo',
            name='generated_by',
        ),
        migrations.RemoveField(
            model_name='return_request',
            name='requested_by',
        ),
        migrations.DeleteModel(
            name='Acknowledgment_Receipt',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='Delivery_Product',
        ),
        migrations.DeleteModel(
            name='Discrepancy_Report',
        ),
        migrations.DeleteModel(
            name='Purchase_Order',
        ),
        migrations.DeleteModel(
            name='Receiving_Memo',
        ),
        migrations.DeleteModel(
            name='Return_Request',
        ),
    ]
