# Generated by Django 5.1.14 on 2025-12-05 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(unique=True)),
                ('branch_address', models.CharField(max_length=150)),
                ('branch_phone', models.CharField(max_length=20)),
                ('branch_email', models.CharField(max_length=100, unique=True)),
                ('branch_is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=50)),
                ('prod_desc', models.CharField(max_length=50)),
                ('prod_unit_of_measure', models.CharField(max_length=20)),
                ('prod_current_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prod_retail_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prod_reorder_threshold', models.IntegerField()),
                ('prod_is_active', models.BooleanField(default=True)),
                ('prod_created_at', models.DateField(auto_now_add=True)),
                ('prod_updated_at', models.DateTimeField(blank=True, null=True)),
                ('prod_sku', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('prod_cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_cat_name', models.CharField(max_length=50)),
                ('prod_cat_desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=20)),
                ('role_description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_on_hand', models.IntegerField(default=0)),
                ('last_updated_at', models.DateField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.product_category'),
        ),
        migrations.CreateModel(
            name='Product_Specification',
            fields=[
                ('prod_spec_id', models.AutoField(primary_key=True, serialize=False)),
                ('spec_name', models.CharField(max_length=50)),
                ('spec_value', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.product')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('user_password', models.CharField(max_length=20)),
                ('user_email', models.CharField(max_length=30, unique=True)),
                ('user_fname', models.CharField(max_length=16)),
                ('user_lname', models.CharField(max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.branch')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.role')),
            ],
        ),
        migrations.CreateModel(
            name='Price_History',
            fields=[
                ('price_id', models.AutoField(primary_key=True, serialize=False)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.user')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory_Transaction',
            fields=[
                ('trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('trans_type', models.CharField(choices=[('stockin', 'Stock In'), ('stockout', 'Stock Out'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.inventory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.user')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.user'),
        ),
    ]
