# Generated by Django 5.2.7 on 2025-11-15 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=12, unique=True)),
                ('branch_address', models.CharField(max_length=60)),
                ('branch_phone', models.CharField(max_length=11)),
                ('branch_email', models.CharField(max_length=30, unique=True)),
                ('branch_is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=20)),
                ('role_description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('user_password', models.CharField(max_length=20)),
                ('user_email', models.CharField(max_length=30, unique=True)),
                ('user_fname', models.CharField(max_length=16)),
                ('user_lname', models.CharField(max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.branch')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.role')),
            ],
        ),
    ]
