# Generated by Django 5.2.7 on 2025-11-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_name',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_description',
            field=models.CharField(max_length=150),
        ),
    ]
