# Generated by Django 5.2.7 on 2025-11-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0002_alter_branch_branch_name_alter_role_role_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_phone',
            field=models.CharField(max_length=20),
        ),
    ]
