# Generated by Django 5.2.7 on 2025-11-15 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0003_alter_branch_branch_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('prod_cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_cat_name', models.CharField(max_length=30)),
                ('prod_cat_desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=30)),
                ('prod_desc', models.CharField(max_length=50)),
                ('prod_unit_of_measure', models.CharField(max_length=20)),
                ('prod_current_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prod_retail_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prod_reorder_threshold', models.IntegerField()),
                ('prod_is_active', models.BooleanField(default=True)),
                ('prod_created_at', models.DateField(auto_now_add=True)),
                ('prod_updated_at', models.DateTimeField(blank=True, null=True)),
                ('prod_sku', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.product_category')),
            ],
        ),
    ]
