# Generated by Django 5.2.7 on 2025-11-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0004_product_category_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product_category',
            name='prod_cat_name',
            field=models.CharField(max_length=50),
        ),
    ]
