# Generated by Django 5.2.7 on 2025-11-15 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0006_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory_Transaction',
            fields=[
                ('trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('trans_type', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.inventory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.user')),
            ],
        ),
    ]
