# Generated by Django 5.2.7 on 2025-11-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0007_inventory_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_transaction',
            name='trans_type',
            field=models.CharField(choices=[('stockin', 'Stock In'), ('stockout', 'Stock Out'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out')], max_length=20),
        ),
    ]
