# Generated by Django 5.2.7 on 2025-11-16 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0008_alter_inventory_transaction_trans_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price_History',
            fields=[
                ('price_id', models.AutoField(primary_key=True, serialize=False)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.user')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Specification',
            fields=[
                ('prod_spec_id', models.AutoField(primary_key=True, serialize=False)),
                ('spec_name', models.CharField(max_length=50)),
                ('spec_value', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.product')),
            ],
        ),
    ]
