# Generated by Django 5.1.7 on 2025-11-23 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0009_price_history_product_specification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_date', models.DateTimeField()),
                ('expected_date', models.DateTimeField()),
                ('delivery_status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('partial', 'Partially Delivered')], default='scheduled', max_length=20)),
                ('delivery_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_deliveries', to='ERP.user')),
            ],
        ),
        migrations.CreateModel(
            name='Acknowledgment_Receipt',
            fields=[
                ('ar_id', models.AutoField(primary_key=True, serialize=False)),
                ('ar_number', models.CharField(max_length=50, unique=True)),
                ('ar_date', models.DateTimeField()),
                ('ar_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_acknowledgment_receipts', to='ERP.user')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.delivery')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_Product',
            fields=[
                ('delivery_prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_ordered', models.IntegerField()),
                ('quantity_delivered', models.IntegerField()),
                ('quantity_accepted', models.IntegerField()),
                ('quantity_rejected', models.IntegerField()),
                ('condition', models.CharField(blank=True, max_length=255, null=True)),
                ('prod_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('partial', 'Partially Accepted')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.delivery')),
                ('flagged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flagged_deliveries', to='ERP.user')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.product')),
            ],
        ),
        migrations.CreateModel(
            name='Discrepancy_Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('quantity', 'Quantity Discrepancy'), ('quality', 'Quality Issue'), ('damage', 'Damaged Goods'), ('missing', 'Missing Items')], max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.delivery')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_discrepancies', to='ERP.user')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Order',
            fields=[
                ('po_id', models.AutoField(primary_key=True, serialize=False)),
                ('po_number', models.CharField(max_length=50, unique=True)),
                ('po_date', models.DateTimeField()),
                ('supplier', models.CharField(max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.user')),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='po_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.purchase_order'),
        ),
        migrations.CreateModel(
            name='Receiving_Memo',
            fields=[
                ('rm_id', models.AutoField(primary_key=True, serialize=False)),
                ('rm_number', models.CharField(max_length=50, unique=True)),
                ('rm_date', models.DateTimeField()),
                ('rm_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.delivery')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_receiving_memos', to='ERP.user')),
            ],
        ),
        migrations.CreateModel(
            name='Return_Request',
            fields=[
                ('return_id', models.AutoField(primary_key=True, serialize=False)),
                ('return_reason', models.TextField()),
                ('return_date', models.DateTimeField()),
                ('return_status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('quantity_to_return', models.IntegerField()),
                ('return_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.delivery_product')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_returns', to='ERP.user')),
            ],
        ),
    ]
