# Generated by Django 5.2.8 on 2025-11-19 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ERP', '0009_price_history_product_specification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('req_id', models.AutoField(primary_key=True, serialize=False)),
                ('req_type', models.CharField(choices=[('INV_REPLENISHMENT', 'Inventory Replenishment'), ('INTERNAL_TRANSFER', 'Internal Transfer')], max_length=30)),
                ('req_main_status', models.CharField(choices=[('PENDING_CUSTODIAN', 'Pending Custodian Approval'), ('PENDING_TOP_MGMT', 'Pending Top Management Approval'), ('APPROVED_REQUISITION', 'Approved Requisition'), ('PO_APPROVAL', 'PO Approval'), ('TO_BE_DELIVERED', 'To be Delivered'), ('INSPECTION', 'Inspection'), ('FULFILLED', 'Request Fulfilled')], max_length=40)),
                ('req_substatus', models.CharField(choices=[('RFQ_CREATED', 'RFQ Created'), ('PENDING_PO', 'Pending Purchase Order'), ('PO_PENDING_CUSTODIAN', 'PO Pending Custodian Approval'), ('PO_PENDING_TOP_MGMT', 'PO Pending Top Management Approval'), ('PO_APPROVED', 'PO Approved'), ('PO_SENT_TO_SUPPLIER', 'PO Sent to Supplier'), ('PRODUCTS_RECEIVED', 'Products Received'), ('INSPECTING', 'Inspecting'), ('IN_TRANSIT', 'In Transit'), ('NONE', 'None')], default='NONE', max_length=40)),
                ('req_requested_date', models.DateTimeField(auto_now_add=True)),
                ('req_date_required', models.DateField(blank=True, null=True)),
                ('req_notes', models.TextField(blank=True, null=True)),
                ('req_rejection_reason', models.TextField(blank=True, null=True)),
                ('req_approval_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_receipt_num', models.CharField(blank=True, max_length=100, null=True)),
                ('rfq_pdf', models.FileField(blank=True, null=True, upload_to='rfq/')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisition_approver', to='ERP.user')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.branch')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.user')),
            ],
        ),
        migrations.CreateModel(
            name='RequisitionItem',
            fields=[
                ('req_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('uom', models.CharField(max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.product')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Requisition.requisition')),
            ],
        ),
        migrations.CreateModel(
            name='RequisitionStatusTimeline',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('main_status', models.CharField(choices=[('PENDING_CUSTODIAN', 'Pending Custodian Approval'), ('PENDING_TOP_MGMT', 'Pending Top Management Approval'), ('APPROVED_REQUISITION', 'Approved Requisition'), ('PO_APPROVAL', 'PO Approval'), ('TO_BE_DELIVERED', 'To be Delivered'), ('INSPECTION', 'Inspection'), ('FULFILLED', 'Request Fulfilled')], max_length=40)),
                ('sub_status', models.CharField(blank=True, choices=[('RFQ_CREATED', 'RFQ Created'), ('PENDING_PO', 'Pending Purchase Order'), ('PO_PENDING_CUSTODIAN', 'PO Pending Custodian Approval'), ('PO_PENDING_TOP_MGMT', 'PO Pending Top Management Approval'), ('PO_APPROVED', 'PO Approved'), ('PO_SENT_TO_SUPPLIER', 'PO Sent to Supplier'), ('PRODUCTS_RECEIVED', 'Products Received'), ('INSPECTING', 'Inspecting'), ('IN_TRANSIT', 'In Transit'), ('NONE', 'None')], max_length=40, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(blank=True, max_length=40, null=True)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='Requisition.requisition')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERP.user')),
            ],
        ),
    ]
