# Generated by Django 5.1.14 on 2025-11-17 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ERP', '0009_price_history_product_specification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('req_id', models.AutoField(primary_key=True, serialize=False)),
                ('req_type', models.CharField(choices=[('INV_REPLENISHMENT', 'Inventory Replenishment'), ('INTERNAL_TRANSFER', 'Internal Transfer')], max_length=30)),
                ('req_status', models.CharField(choices=[('CUSTODIAN_REVIEW', 'Custodian Review'), ('MANAGEMENT_APPROVAL', 'Management Approval'), ('PURCHASEMENT', 'Purchasement'), ('READY_FOR_SOURCING', 'Ready for Sourcing'), ('RFQ_CREATED', 'RFQ Created'), ('CANVASSING_COMPLETED', 'Canvassing Completed'), ('PENDING_PO_APPROVAL', 'Pending PO Approval'), ('PO_APPROVED', 'PO Approved'), ('PO_REJECTED', 'PO Rejected')], max_length=30)),
                ('req_requested_date', models.DateField()),
                ('req_date_req', models.DateField()),
                ('req_notes', models.TextField(blank=True, null=True)),
                ('req_rejection_reason', models.TextField(blank=True, null=True)),
                ('req_approval_date', models.DateField(blank=True, null=True)),
                ('req_delivery_receipt_num', models.CharField(blank=True, max_length=100, null=True)),
                ('rfq_pdf', models.FileField(blank=True, null=True, upload_to='rfqs/')),
                ('ack_knowledgement_id', models.IntegerField(blank=True, null=True)),
                ('receiving_memo_id', models.IntegerField(blank=True, null=True)),
                ('approved_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requisitions', to='ERP.user')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.user')),
            ],
        ),
        migrations.CreateModel(
            name='RequisitionItem',
            fields=[
                ('req_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('req_item_quantity', models.IntegerField()),
                ('req_item_uom', models.CharField(max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.product')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Requisition.requisition')),
            ],
        ),
        migrations.CreateModel(
            name='RequisitionProgress',
            fields=[
                ('req_prog_id', models.AutoField(primary_key=True, serialize=False)),
                ('req_prog_action', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ESCALATED', 'Escalated')], max_length=20)),
                ('req_prog_comment', models.TextField(blank=True, null=True)),
                ('req_prog_action_date', models.DateField()),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Requisition.requisition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.user')),
            ],
        ),
    ]
