# Generated by Django 5.1.14 on 2025-11-19 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0009_price_history_product_specification'),
        ('Requisition', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisition',
            old_name='req_delivery_receipt_num',
            new_name='delivery_receipt_num',
        ),
        migrations.RenameField(
            model_name='requisition',
            old_name='user',
            new_name='requested_by',
        ),
        migrations.RenameField(
            model_name='requisitionitem',
            old_name='req_item_quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='requisitionitem',
            old_name='req_item_uom',
            new_name='uom',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='ack_knowledgement_id',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='approved_by_user',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='receiving_memo_id',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='req_date_req',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='req_status',
        ),
        migrations.AddField(
            model_name='requisition',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisition_approver', to='ERP.user'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='req_date_required',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='req_main_status',
            field=models.CharField(choices=[('PENDING_CUSTODIAN', 'Pending Custodian Approval'), ('PENDING_TOP_MGMT', 'Pending Top Management Approval'), ('APPROVED_REQUISITION', 'Approved Requisition'), ('PO_APPROVAL', 'PO Approval'), ('TO_BE_DELIVERED', 'To be Delivered'), ('INSPECTION', 'Inspection'), ('FULFILLED', 'Request Fulfilled')], default='Pending Custodian Approval', max_length=40),
        ),
        migrations.AddField(
            model_name='requisition',
            name='req_substatus',
            field=models.CharField(choices=[('RFQ_CREATED', 'RFQ Created'), ('PENDING_PO', 'Pending Purchase Order'), ('PO_PENDING_CUSTODIAN', 'PO Pending Custodian Approval'), ('PO_PENDING_TOP_MGMT', 'PO Pending Top Management Approval'), ('PO_APPROVED', 'PO Approved'), ('PO_SENT_TO_SUPPLIER', 'PO Sent to Supplier'), ('PRODUCTS_RECEIVED', 'Products Received'), ('INSPECTING', 'Inspecting'), ('IN_TRANSIT', 'In Transit'), ('NONE', 'None')], default='NONE', max_length=40),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='req_approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='req_requested_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='rfq_pdf',
            field=models.FileField(blank=True, null=True, upload_to='rfq/'),
        ),
        migrations.AlterField(
            model_name='requisitionitem',
            name='requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Requisition.requisition'),
        ),
        migrations.CreateModel(
            name='RequisitionStatusTimeline',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('main_status', models.CharField(choices=[('PENDING_CUSTODIAN', 'Pending Custodian Approval'), ('PENDING_TOP_MGMT', 'Pending Top Management Approval'), ('APPROVED_REQUISITION', 'Approved Requisition'), ('PO_APPROVAL', 'PO Approval'), ('TO_BE_DELIVERED', 'To be Delivered'), ('INSPECTION', 'Inspection'), ('FULFILLED', 'Request Fulfilled')], max_length=40)),
                ('sub_status', models.CharField(blank=True, choices=[('RFQ_CREATED', 'RFQ Created'), ('PENDING_PO', 'Pending Purchase Order'), ('PO_PENDING_CUSTODIAN', 'PO Pending Custodian Approval'), ('PO_PENDING_TOP_MGMT', 'PO Pending Top Management Approval'), ('PO_APPROVED', 'PO Approved'), ('PO_SENT_TO_SUPPLIER', 'PO Sent to Supplier'), ('PRODUCTS_RECEIVED', 'Products Received'), ('INSPECTING', 'Inspecting'), ('IN_TRANSIT', 'In Transit'), ('NONE', 'None')], max_length=40, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(blank=True, max_length=40, null=True)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='Requisition.requisition')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERP.user')),
            ],
        ),
        migrations.DeleteModel(
            name='RequisitionProgress',
        ),
    ]
