# Generated by Django 5.2.8 on 2025-11-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requisition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='req_main_status',
            field=models.CharField(choices=[('PENDING_CUSTODIAN', 'Pending Custodian Approval'), ('PENDING_TOP_MGMT', 'Pending Top Management Approval'), ('APPROVED_REQUISITION', 'Approved Requisition'), ('PO_APPROVAL', 'PO Approval'), ('TO_BE_DELIVERED', 'To be Delivered'), ('INSPECTION', 'Inspection'), ('FULFILLED', 'Request Fulfilled')], max_length=100),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='req_substatus',
            field=models.CharField(choices=[('RFQ_CREATED', 'RFQ Created'), ('PENDING_PO', 'Pending Purchase Order'), ('PO_PENDING_CUSTODIAN', 'PO Pending Custodian Approval'), ('PO_PENDING_TOP_MGMT', 'PO Pending Top Management Approval'), ('PO_APPROVED', 'PO Approved'), ('PO_SENT_TO_SUPPLIER', 'PO Sent to Supplier'), ('PRODUCTS_RECEIVED', 'Products Received'), ('INSPECTING', 'Inspecting'), ('IN_TRANSIT', 'In Transit'), ('NONE', 'None')], default='NONE', max_length=100),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='req_type',
            field=models.CharField(choices=[('INV_REPLENISHMENT', 'Inventory Replenishment'), ('INTERNAL_TRANSFER', 'Internal Transfer')], max_length=100),
        ),
        migrations.AlterField(
            model_name='requisitionstatustimeline',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requisitionstatustimeline',
            name='main_status',
            field=models.CharField(choices=[('PENDING_CUSTODIAN', 'Pending Custodian Approval'), ('PENDING_TOP_MGMT', 'Pending Top Management Approval'), ('APPROVED_REQUISITION', 'Approved Requisition'), ('PO_APPROVAL', 'PO Approval'), ('TO_BE_DELIVERED', 'To be Delivered'), ('INSPECTION', 'Inspection'), ('FULFILLED', 'Request Fulfilled')], max_length=100),
        ),
        migrations.AlterField(
            model_name='requisitionstatustimeline',
            name='sub_status',
            field=models.CharField(blank=True, choices=[('RFQ_CREATED', 'RFQ Created'), ('PENDING_PO', 'Pending Purchase Order'), ('PO_PENDING_CUSTODIAN', 'PO Pending Custodian Approval'), ('PO_PENDING_TOP_MGMT', 'PO Pending Top Management Approval'), ('PO_APPROVED', 'PO Approved'), ('PO_SENT_TO_SUPPLIER', 'PO Sent to Supplier'), ('PRODUCTS_RECEIVED', 'Products Received'), ('INSPECTING', 'Inspecting'), ('IN_TRANSIT', 'In Transit'), ('NONE', 'None')], max_length=100, null=True),
        ),
    ]
