# Generated by Django 5.2.8 on 2025-11-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requisition', '0002_alter_requisition_req_main_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='rfq_pdf',
        ),
        migrations.AddField(
            model_name='requisition',
            name='rf_file',
            field=models.FileField(blank=True, null=True, upload_to='rfs/'),
        ),
    ]
