# Generated by Django 5.2.7 on 2025-11-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requisition', '0003_remove_requisition_rfq_pdf_requisition_rf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='req_substatus',
            field=models.CharField(choices=[('RFQ_CREATED', 'RFQ Created'), ('PENDING_PO', 'Pending Purchase Order'), ('PO_CUSTODIAN_APPROVAL', 'Custodian reviewed and approved'), ('PO_TOP_MANAGEMENT_APPROVAL', 'Approved by Top Management'), ('PO_APPROVED', 'PO Approved'), ('PO_SENT_TO_SUPPLIER', 'PO Sent to Supplier'), ('PRODUCTS_RECEIVED', 'Products Received'), ('INSPECTING', 'Inspecting'), ('IN_TRANSIT', 'In Transit'), ('NONE', 'None')], default='NONE', max_length=100),
        ),
        migrations.AlterField(
            model_name='requisitionstatustimeline',
            name='sub_status',
            field=models.CharField(blank=True, choices=[('RFQ_CREATED', 'RFQ Created'), ('PENDING_PO', 'Pending Purchase Order'), ('PO_CUSTODIAN_APPROVAL', 'Custodian reviewed and approved'), ('PO_TOP_MANAGEMENT_APPROVAL', 'Approved by Top Management'), ('PO_APPROVED', 'PO Approved'), ('PO_SENT_TO_SUPPLIER', 'PO Sent to Supplier'), ('PRODUCTS_RECEIVED', 'Products Received'), ('INSPECTING', 'Inspecting'), ('IN_TRANSIT', 'In Transit'), ('NONE', 'None')], max_length=100, null=True),
        ),
    ]
