# Generated by Django 5.1.7 on 2025-11-24 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Requisition', '0004_alter_requisition_req_substatus_and_more'),
        ('Requisition', '0004_requisition_sender_branch_requisition_sender_user_and_more'),
    ]

    operations = [
    ]
