# Generated by Django 5.1.14 on 2025-12-02 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchasing', '0004_remove_rfq_item_requisition_and_more'),
        ('Requisition', '0004_alter_requisition_req_substatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='rfq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to='Purchasing.rfq'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='req_substatus',
            field=models.CharField(choices=[('RFQ_CREATED', 'RFQ Created'), ('QUOTATIONS_COMPLETED', 'Quotations Completed'), ('PENDING_PO', 'Pending Purchase Order'), ('PO_CUSTODIAN_APPROVAL', 'Custodian reviewed and approved'), ('PO_TOP_MANAGEMENT_APPROVAL', 'Approved by Top Management'), ('PO_APPROVED', 'PO Approved'), ('PO_SENT_TO_SUPPLIER', 'PO Sent to Supplier'), ('PRODUCTS_RECEIVED', 'Products Received'), ('INSPECTING', 'Inspecting'), ('IN_TRANSIT', 'In Transit'), ('NONE', 'None')], default='NONE', max_length=100),
        ),
        migrations.AlterField(
            model_name='requisitionstatustimeline',
            name='sub_status',
            field=models.CharField(blank=True, choices=[('RFQ_CREATED', 'RFQ Created'), ('QUOTATIONS_COMPLETED', 'Quotations Completed'), ('PENDING_PO', 'Pending Purchase Order'), ('PO_CUSTODIAN_APPROVAL', 'Custodian reviewed and approved'), ('PO_TOP_MANAGEMENT_APPROVAL', 'Approved by Top Management'), ('PO_APPROVED', 'PO Approved'), ('PO_SENT_TO_SUPPLIER', 'PO Sent to Supplier'), ('PRODUCTS_RECEIVED', 'Products Received'), ('INSPECTING', 'Inspecting'), ('IN_TRANSIT', 'In Transit'), ('NONE', 'None')], max_length=100, null=True),
        ),
    ]
