# Generated by Django 5.1.14 on 2025-12-03 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchasing', '0006_remove_purchase_order_requisition'),
        ('Requisition', '0005_requisition_rfq_alter_requisition_req_substatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='po',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to='Purchasing.purchase_order'),
        ),
    ]
