# Generated by Django 5.1.7 on 2025-11-29 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ERP', '0011_remove_delivery_po_id_remove_delivery_received_by_and_more'),
        ('Requisition', '0004_alter_requisition_req_substatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('sup_id', models.AutoField(primary_key=True, serialize=False)),
                ('sup_name', models.CharField(max_length=255)),
                ('sup_phone', models.CharField(max_length=50)),
                ('sup_email', models.CharField(blank=True, max_length=255, null=True)),
                ('sup_address', models.TextField(blank=True, null=True)),
                ('sup_contact_person', models.CharField(default='Unknown', max_length=50)),
                ('sup_payment_terms', models.TextField(blank=True, null=True)),
                ('sup_delivery_terms', models.TextField(blank=True, null=True)),
                ('sup_is_active', models.BooleanField(default=True)),
                ('sup_created_at', models.DateTimeField(auto_now_add=True)),
                ('sup_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_date', models.DateTimeField()),
                ('expected_date', models.DateTimeField()),
                ('delivery_status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('partial', 'Partially Delivered')], default='scheduled', max_length=20)),
                ('delivery_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_deliveries', to='ERP.user')),
            ],
        ),
        migrations.CreateModel(
            name='Acknowledgment_Receipt',
            fields=[
                ('ar_id', models.AutoField(primary_key=True, serialize=False)),
                ('ar_number', models.CharField(max_length=50, unique=True)),
                ('ar_date', models.DateTimeField()),
                ('ar_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_acknowledgment_receipts', to='ERP.user')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Property_Custodian.delivery')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_Product',
            fields=[
                ('delivery_prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_ordered', models.IntegerField()),
                ('quantity_delivered', models.IntegerField()),
                ('quantity_accepted', models.IntegerField()),
                ('quantity_rejected', models.IntegerField()),
                ('condition', models.CharField(blank=True, max_length=255, null=True)),
                ('prod_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('partial', 'Partially Accepted')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Property_Custodian.delivery')),
                ('flagged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flagged_deliveries', to='ERP.user')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.product')),
            ],
        ),
        migrations.CreateModel(
            name='Discrepancy_Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('quantity', 'Quantity Discrepancy'), ('quality', 'Quality Issue'), ('damage', 'Damaged Goods'), ('missing', 'Missing Items')], max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Property_Custodian.delivery')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_discrepancies', to='ERP.user')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Order',
            fields=[
                ('po_id', models.AutoField(primary_key=True, serialize=False)),
                ('po_status', models.CharField(max_length=50)),
                ('po_date_sent_to_sup', models.DateField(blank=True, null=True)),
                ('po_eta', models.DateField(blank=True, null=True)),
                ('po_total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('po_approval_date', models.DateField(blank=True, null=True)),
                ('po_rejection_reason', models.TextField(blank=True, null=True)),
                ('po_created_at', models.DateTimeField(auto_now_add=True)),
                ('po_pdf', models.FileField(blank=True, null=True, upload_to='po_pdfs/')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.branch')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Requisition.requisition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.user')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Property_Custodian.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='po_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Property_Custodian.purchase_order'),
        ),
        migrations.CreateModel(
            name='Purchase_Order_Item',
            fields=[
                ('po_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('po_item_ordered_quantity', models.IntegerField()),
                ('po_item_unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('po_item_line_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Property_Custodian.purchase_order')),
            ],
        ),
        migrations.CreateModel(
            name='Receiving_Memo',
            fields=[
                ('rm_id', models.AutoField(primary_key=True, serialize=False)),
                ('rm_number', models.CharField(max_length=50, unique=True)),
                ('rm_date', models.DateTimeField()),
                ('rm_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Property_Custodian.delivery')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_receiving_memos', to='ERP.user')),
            ],
        ),
        migrations.CreateModel(
            name='Return_Request',
            fields=[
                ('return_id', models.AutoField(primary_key=True, serialize=False)),
                ('return_reason', models.TextField()),
                ('return_date', models.DateTimeField()),
                ('return_status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('quantity_to_return', models.IntegerField()),
                ('return_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Property_Custodian.delivery_product')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_returns', to='ERP.user')),
            ],
        ),
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('rfq_id', models.AutoField(primary_key=True, serialize=False)),
                ('rfq_created_at', models.DateTimeField(auto_now_add=True)),
                ('rfq_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Requisition.requisition')),
            ],
        ),
        migrations.CreateModel(
            name='RFQ_Item',
            fields=[
                ('rfq_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('rfq_item_req_qty', models.IntegerField(default=0)),
                ('rfq_item_req_uom', models.CharField(max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.product')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Requisition.requisition')),
            ],
        ),
        migrations.CreateModel(
            name='RFQ_Supplier',
            fields=[
                ('rfq_sup_id', models.AutoField(primary_key=True, serialize=False)),
                ('rfq_date_sent', models.DateTimeField(auto_now_add=True)),
                ('date_responded', models.DateTimeField(blank=True, null=True)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Requisition.requisition')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Property_Custodian.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_Category',
            fields=[
                ('sup_cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.product_category')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Property_Custodian.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_Product',
            fields=[
                ('sup_prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('sup_prod_code', models.CharField(max_length=50)),
                ('sup_prod_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sup_prod_last_updated_price', models.DateTimeField(auto_now_add=True)),
                ('sup_prod_is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Property_Custodian.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_Quotation',
            fields=[
                ('sup_qtn_id', models.AutoField(primary_key=True, serialize=False)),
                ('sup_qtn_total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sup_qtn_eta', models.DateField(blank=True, null=True)),
                ('sup_qtn_valid_until', models.DateField(blank=True, null=True)),
                ('sup_qtn_pdf', models.FileField(blank=True, null=True, upload_to='supplier_quotations/')),
                ('sup_qtn_created_at', models.DateTimeField(auto_now_add=True)),
                ('rfq_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Property_Custodian.rfq_supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_Quotation_Item',
            fields=[
                ('sup_qtn_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('sup_qtn_item_unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.product')),
                ('rfq_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Property_Custodian.rfq_item')),
                ('supplier_quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Property_Custodian.supplier_quotation')),
            ],
        ),
    ]
