# Generated by Django 5.1.7 on 2025-11-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property_Custodian', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_order',
            name='po_status',
        ),
        migrations.AddField(
            model_name='purchase_order',
            name='po_main_status',
            field=models.CharField(choices=[('PENDING_CUSTODIAN', 'Pending Custodian Approval'), ('PENDING_TOP_MGMT', 'Pending Top Management Approval'), ('APPROVED_REQUISITION', 'Approved Requisition'), ('PO_APPROVAL', 'PO Approval'), ('TO_BE_DELIVERED', 'To be Delivered'), ('INSPECTION', 'Inspection'), ('FULFILLED', 'Request Fulfilled')], default='PO_APPROVAL', max_length=50),
        ),
        migrations.AddField(
            model_name='purchase_order',
            name='po_substatus',
            field=models.CharField(choices=[('RFQ_CREATED', 'RFQ Created'), ('PENDING_PO', 'Pending Purchase Order'), ('PO_CUSTODIAN_APPROVAL', 'Custodian reviewed and approved'), ('PO_TOP_MANAGEMENT_APPROVAL', 'Approved by Top Management'), ('PO_APPROVED', 'PO Approved'), ('PO_SENT_TO_SUPPLIER', 'PO Sent to Supplier'), ('PRODUCTS_RECEIVED', 'Products Received'), ('INSPECTING', 'Inspecting'), ('IN_TRANSIT', 'In Transit'), ('NONE', 'None')], default='PO_CUSTODIAN_APPROVAL', max_length=100),
        ),
    ]
