# Generated by Django 5.1.7 on 2025-12-04 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0011_remove_delivery_po_id_remove_delivery_received_by_and_more'),
        ('Property_Custodian', '0005_alter_delivery_options_and_more'),
        ('Requisition', '0004_alter_requisition_req_substatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='condition_notes',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='product',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='quantity_accepted',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='quantity_delivered',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='quantity_ordered',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='quantity_rejected',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='received_by',
        ),
        migrations.AddField(
            model_name='delivery',
            name='inspected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_deliveries', to='ERP.user'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='requisition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Requisition.requisition'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries_made', to='Property_Custodian.supplier'),
        ),
        migrations.CreateModel(
            name='Delivery_Item',
            fields=[
                ('delivery_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_ordered', models.IntegerField()),
                ('quantity_delivered', models.IntegerField(default=0)),
                ('quantity_accepted', models.IntegerField(default=0)),
                ('inspection_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Property_Custodian.delivery')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.product')),
                ('purchase_order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Property_Custodian.purchase_order_item')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('delivery', 'purchase_order_item')},
            },
        ),
        migrations.AlterField(
            model_name='return_request',
            name='delivery_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Property_Custodian.delivery_item'),
        ),
        migrations.DeleteModel(
            name='Delivery_Product',
        ),
    ]
