# Generated by Django 5.1.7 on 2025-12-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property_Custodian', '0010_deliveryitem_branch_alter_delivery_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='po_substatus',
            field=models.CharField(choices=[('RFQ_CREATED', 'RFQ Created'), ('PENDING_PO', 'Pending Purchase Order'), ('PO_CUSTODIAN_APPROVAL', 'Custodian reviewed and approved'), ('PO_TOP_MANAGEMENT_APPROVAL', 'Approved by Top Management'), ('PO_APPROVED', 'PO Approved'), ('PO_SENT_TO_SUPPLIER', 'PO Sent to Supplier'), ('PRODUCTS_RECEIVED', 'Products Received'), ('INSPECTING', 'Inspecting'), ('IN_TRANSIT', 'In Transit'), ('RECEIVED', 'Received'), ('NONE', 'None')], default='PO_CUSTODIAN_APPROVAL', max_length=100),
        ),
    ]
