# Generated by Django 5.1.14 on 2025-12-06 10:58

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ERP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQ_Supplier',
            fields=[
                ('rfq_sup_id', models.AutoField(primary_key=True, serialize=False)),
                ('rfq_date_sent', models.DateTimeField(auto_now_add=True)),
                ('date_responded', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('sup_id', models.AutoField(primary_key=True, serialize=False)),
                ('sup_name', models.CharField(max_length=255)),
                ('sup_phone', models.CharField(max_length=50)),
                ('sup_email', models.CharField(blank=True, max_length=255, null=True)),
                ('sup_address', models.TextField(blank=True, null=True)),
                ('sup_contact_person', models.CharField(default='Unknown', max_length=50)),
                ('sup_payment_terms', models.TextField(blank=True, null=True)),
                ('sup_delivery_terms', models.TextField(blank=True, null=True)),
                ('sup_is_active', models.BooleanField(default=True)),
                ('sup_created_at', models.DateTimeField(auto_now_add=True)),
                ('sup_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_Category',
            fields=[
                ('sup_cat_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_Product',
            fields=[
                ('sup_prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('sup_prod_code', models.CharField(max_length=50)),
                ('sup_prod_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sup_prod_last_updated_price', models.DateTimeField(auto_now_add=True)),
                ('sup_prod_is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_Product_PriceHistory',
            fields=[
                ('price_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_Quotation',
            fields=[
                ('sup_qtn_id', models.AutoField(primary_key=True, serialize=False)),
                ('sup_qtn_total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sup_qtn_eta', models.DateField(blank=True, null=True)),
                ('sup_qtn_valid_until', models.DateField(blank=True, null=True)),
                ('sup_qtn_pdf', models.FileField(blank=True, null=True, upload_to='supplier_quotations/')),
                ('sup_qtn_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_Quotation_Item',
            fields=[
                ('sup_qtn_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('sup_qtn_item_unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Order',
            fields=[
                ('po_id', models.AutoField(primary_key=True, serialize=False)),
                ('po_main_status', models.CharField(choices=[('PENDING_CUSTODIAN', 'Pending Custodian Approval'), ('PENDING_TOP_MGMT', 'Pending Top Management Approval'), ('APPROVED_REQUISITION', 'Approved Requisition'), ('PO_APPROVAL', 'PO Approval'), ('TO_BE_DELIVERED', 'To be Delivered'), ('INSPECTION', 'Inspection'), ('FULFILLED', 'Request Fulfilled')], default='PO_APPROVAL', max_length=50)),
                ('po_substatus', models.CharField(choices=[('RFQ_CREATED', 'RFQ Created'), ('PENDING_PO', 'Pending Purchase Order'), ('PO_CUSTODIAN_APPROVAL', 'Custodian reviewed and approved'), ('PO_TOP_MANAGEMENT_APPROVAL', 'Approved by Top Management'), ('PO_APPROVED', 'PO Approved'), ('PO_SENT_TO_SUPPLIER', 'PO Sent to Supplier'), ('PRODUCTS_RECEIVED', 'Products Received'), ('INSPECTING', 'Inspecting'), ('IN_TRANSIT', 'In Transit'), ('RECEIVED', 'Received'), ('NONE', 'None')], default='NONE', max_length=100)),
                ('po_date_sent_to_sup', models.DateField(blank=True, null=True)),
                ('po_eta', models.DateField(blank=True, null=True)),
                ('po_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('po_total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('po_approval_date', models.DateField(blank=True, null=True)),
                ('po_rejection_reason', models.TextField(blank=True, null=True)),
                ('po_created_at', models.DateTimeField(auto_now_add=True)),
                ('po_pdf', models.FileField(blank=True, null=True, upload_to='po_pdfs/')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.user')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Order_Item',
            fields=[
                ('po_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('po_item_ordered_quantity', models.IntegerField()),
                ('po_item_unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('po_item_line_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchasing.purchase_order')),
            ],
        ),
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('rfq_id', models.AutoField(primary_key=True, serialize=False)),
                ('rfq_created_at', models.DateTimeField(auto_now_add=True)),
                ('rfq_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.user')),
            ],
        ),
        migrations.CreateModel(
            name='RFQ_Item',
            fields=[
                ('rfq_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('rfq_item_req_qty', models.IntegerField(default=0)),
                ('rfq_item_req_uom', models.CharField(max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.product')),
            ],
        ),
    ]
