# Generated by Django 5.1.14 on 2025-12-05 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ERP', '0001_initial'),
        ('Purchasing', '0001_initial'),
        ('Requisition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq_item',
            name='requisition_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfq_items', to='Requisition.requisitionitem'),
        ),
        migrations.AddField(
            model_name='rfq_item',
            name='rfq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Purchasing.rfq'),
        ),
        migrations.AddField(
            model_name='rfq_supplier',
            name='rfq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchasing.rfq'),
        ),
        migrations.AddField(
            model_name='rfq_supplier',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchasing.supplier'),
        ),
        migrations.AddField(
            model_name='purchase_order',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchasing.supplier'),
        ),
        migrations.AddField(
            model_name='supplier_category',
            name='prod_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.product_category'),
        ),
        migrations.AddField(
            model_name='supplier_category',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchasing.supplier'),
        ),
        migrations.AddField(
            model_name='supplier_product',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ERP.product'),
        ),
        migrations.AddField(
            model_name='supplier_product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchasing.supplier'),
        ),
        migrations.AddField(
            model_name='supplier_product_pricehistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERP.user'),
        ),
        migrations.AddField(
            model_name='supplier_product_pricehistory',
            name='supplier_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='Purchasing.supplier_product'),
        ),
        migrations.AddField(
            model_name='supplier_quotation',
            name='rfq_supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchasing.rfq_supplier'),
        ),
        migrations.AddField(
            model_name='supplier_quotation_item',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.product'),
        ),
        migrations.AddField(
            model_name='supplier_quotation_item',
            name='rfq_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchasing.rfq_item'),
        ),
        migrations.AddField(
            model_name='supplier_quotation_item',
            name='supplier_quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchasing.supplier_quotation'),
        ),
    ]
