# Generated by Django 5.1.14 on 2025-12-06 07:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchasing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order',
            name='po_subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
    ]
