# Generated by Django 5.1.14 on 2025-12-06 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchasing', '0002_initial'),
        ('Requisition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order',
            name='requisition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Requisition.requisition'),
            preserve_default=False,
        ),
    ]
