# Generated by Django 5.1.14 on 2025-12-06 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Purchasing', '0003_purchase_order_requisition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_order',
            name='requisition',
        ),
    ]
